package uga.inf453.com;

import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.naming.PartialResultException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class Main extends javax.swing.JFrame {

    Connect connect;
    AjouteMot ajouteMot;
    DefaultTableModel defaultTableModel;
    ResultSet resultSet;
    VerifieTable verifieTable;
    SupprimeLigne supprimeLigne;
    Affichage affichage;
    UpdateTable updateTable;
    RandomWord randomWord;
    int score = 0;
    String nom;
    PreparedStatement preparedStatement;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        affichage = new Affichage();
        connect = new Connect();
        ajouteMot = new AjouteMot();
        verifieTable = new VerifieTable();
        supprimeLigne = new SupprimeLigne();
        updateTable = new UpdateTable();
        randomWord = new RandomWord();
        connect = new Connect();
        ajouteMot = new AjouteMot();
        Create create = new Create();

        randomWord.creerListMot();
        jTableAfficher.removeColumn(jTableAfficher.getColumnModel().getColumn(5)); // on chache la collone id_d dans
                                                                                   // gestion dictionnaire
        jIdDictionnaire.setVisible(false); // on cache le id de dictionnaire dans l'iterface graphic
        affichage.afficherType(jComboType); // affiche les contennus dans la table type tout suit qu'on demarre notre
                                            // systeme

        try {
            create.executeQuery();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Table non crée" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        jtxtFRE = new javax.swing.JTextField();
        jtxtENG = new javax.swing.JTextField();
        jtxtSynonyms = new javax.swing.JTextField();
        jtxtDefinition = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAfficher = new javax.swing.JTable();
        jbtnAdd = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jButtonAfficher = new javax.swing.JButton();
        jButtonResetTableAfficher = new javax.swing.JButton();
        jIdDictionnaire = new javax.swing.JLabel();
        jComboType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonAddType = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIrregulier = new javax.swing.JTable();
        jtxtEnglishVerb = new javax.swing.JTextField();
        jtxtPreterit = new javax.swing.JTextField();
        jtxtPastParticiple = new javax.swing.JTextField();
        jButtonAddIrregulier = new javax.swing.JButton();
        jButtonResetIrregulier = new javax.swing.JButton();
        jButtonUpdateIrregulier = new javax.swing.JButton();
        jButtonAfficherIrregulier = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtxtMotFrancaisVI = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("French Word");

        jLabel2.setText("English Word");

        jLabel3.setText("Synonyme");

        jLabel4.setText("Definition");

        Type.setText("Type");

        jTableAfficher.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mot Francais", "Mot Anglais", "Synonyme", "Type", "Definition", "id_d"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTableAfficher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAfficherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAfficher);

        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jButtonAfficher.setText("Afficher");
        jButtonAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherActionPerformed(evt);
            }
        });

        jButtonResetTableAfficher.setText("Reset");
        jButtonResetTableAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetTableAfficherActionPerformed(evt);
            }
        });

        jIdDictionnaire.setText("id");

        jLabel5.setText("Add un type pour mot qui n'existe pas");

        jButtonAddType.setText("Add un Type");
        jButtonAddType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(36, 36, 36)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jtxtFRE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                212, Short.MAX_VALUE)
                                                                        .addComponent(jtxtENG)
                                                                        .addComponent(jtxtSynonyms)
                                                                        .addComponent(jtxtDefinition))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jbtnReset,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jbtnUpdate,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jbtnDelete,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jbtnAdd,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                                .addGap(56, 56, 56))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jComboType,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 174,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jIdDictionnaire)
                                                .addGap(29, 29, 29))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jButtonAfficher)
                                                                                .addContainerGap(361, Short.MAX_VALUE))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jButtonResetTableAfficher)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(jLabel5,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        247,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(34, 34, 34))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jButtonAddType)
                                                                        .addGap(112, 112, 112)))))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jIdDictionnaire)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jtxtFRE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jtxtENG,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jtxtSynonyms,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(9, 9, 9)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jtxtDefinition,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(57, 57, 57))
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jComboType,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Type,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(53, 53, 53)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 116,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jButtonAfficher)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonResetTableAfficher))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jbtnAdd)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbtnReset)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jbtnUpdate)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbtnDelete)
                                                .addGap(171, 171, 171)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonAddType)))
                                .addGap(53, 53, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Gestion Dictionnaire", jPanel1);

        jLabel6.setText("English Verb");

        jLabel7.setText("Preterit");

        jLabel8.setText("Past Participle");

        jTableIrregulier.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mot Francais", "Mot Anglais", "Preterit", "Past Participle"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTableIrregulier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableIrregulierMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(jTableIrregulier);

        jButtonAddIrregulier.setText("Add New Verb");
        jButtonAddIrregulier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddIrregulierActionPerformed(evt);
            }
        });

        jButtonResetIrregulier.setText("Reset");
        jButtonResetIrregulier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetIrregulierActionPerformed(evt);
            }
        });

        jButtonUpdateIrregulier.setText("Update");
        jButtonUpdateIrregulier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateIrregulierActionPerformed(evt);
            }
        });

        jButtonAfficherIrregulier.setText("Afficher");
        jButtonAfficherIrregulier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherIrregulierActionPerformed(evt);
            }
        });

        jLabel10.setText("French Word");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonAfficherIrregulier)
                                                .addContainerGap(367, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel10))
                                                .addGap(24, 24, 24)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jtxtEnglishVerb,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 157,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jtxtPreterit)
                                                        .addComponent(jtxtPastParticiple)
                                                        .addComponent(jtxtMotFrancaisVI))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButtonAddIrregulier)
                                                        .addComponent(jButtonResetIrregulier)
                                                        .addComponent(jButtonUpdateIrregulier))
                                                .addGap(35, 35, 35)))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonAddIrregulier)
                                        .addComponent(jLabel10)
                                        .addComponent(jtxtMotFrancaisVI, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButtonResetIrregulier)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonUpdateIrregulier)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        111, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 155,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonAfficherIrregulier))
                                                .addGap(41, 41, 41))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jtxtEnglishVerb,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jtxtPreterit,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jtxtPastParticiple,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)))));

        jTabbedPane1.addTab("Gestion verbes irréguliers", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 948, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 462, Short.MAX_VALUE));

        jTabbedPane1.addTab("Test Jeux", jPanel3);

        jLabel9.setText("Gestion De Donnees");

        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 186,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(115, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbtnExit)
                                .addGap(234, 234, 234)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41,
                                        Short.MAX_VALUE)
                                .addComponent(jbtnExit)
                                .addGap(21, 21, 21)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtnAddActionPerformed
        String motFrancais = jtxtFRE.getText();
        String definition = jtxtDefinition.getText();
        String motSynonyme = jtxtSynonyms.getText();
        String motAnglais = jtxtENG.getText();
        String type = jComboType.getModel().getSelectedItem().toString();

        try {
            if (motAnglais.equals("") || type.equals("") || motSynonyme.equals("") || motFrancais.equals("")
                    || definition.equals("")) {
                JOptionPane.showMessageDialog(this, "Le(s) champ(s) sont vide(s)");
            } else {
                if (verifieTable.verifieDictionnaire(motFrancais, motAnglais, motSynonyme, type, definition) == true) {
                    JOptionPane.showMessageDialog(rootPane, "Dictionnaire deja existent");
                } else {

                    ajouteMot.dictionnaire(motFrancais.toLowerCase(), motAnglais.toLowerCase(),
                            motSynonyme.toLowerCase(), type, definition.toLowerCase());

                    if (verifieTable.verifieEquivalence(motAnglais, motFrancais) == false) {
                        ajouteMot.ajouteEquivalence(motFrancais.toLowerCase(), motAnglais.toLowerCase());
                    }
                    JOptionPane.showMessageDialog(rootPane, "mot add dans dictionnaire");
                }

            }
        } catch (HeadlessException | SQLException e) {
            System.err.println(e.getMessage());
        }
    }// GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtnResetActionPerformed
        jtxtFRE.setText("");
        jtxtENG.setText("");
        jtxtSynonyms.setText("");
        jtxtDefinition.setText("");
    }// GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtnUpdateActionPerformed
        String motFrancais = jtxtFRE.getText();
        String motAnglais = jtxtENG.getText();
        String motSynonyme = jtxtSynonyms.getText();
        String type = jComboType.getModel().getSelectedItem().toString();
        String definition = jtxtDefinition.getText();
        int idDictionnaire = Integer.parseInt(jIdDictionnaire.getText());

        try {

            if (motAnglais.equals("") || type.equals("") || motSynonyme.equals("") || motFrancais.equals("")
                    || definition.equals("")) {
                JOptionPane.showMessageDialog(this, "Le(s) champ(s) sont vide(s)");
            } else {
                if (verifieTable.verifieDictionnaire(motFrancais, motAnglais, motSynonyme, type, definition) == true) {
                    JOptionPane.showMessageDialog(rootPane, "Dictionnaire deja existant");
                } else {
                    updateTable.updateDictionnaire(motFrancais.toLowerCase(), motAnglais.toLowerCase(),
                            motSynonyme.toLowerCase(), type, definition.toLowerCase(), idDictionnaire);
                    JOptionPane.showMessageDialog(rootPane, "update reussi");
                }
            }

        } catch (SQLException ex) {

        }
    }// GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtnDeleteActionPerformed
        int id = Integer.parseInt(jIdDictionnaire.getText());
        supprimeLigne.delete(id);
    }// GEN-LAST:event_jbtnDeleteActionPerformed

    private void jButtonAfficherActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAfficherActionPerformed
        affichage.afficher((DefaultTableModel) jTableAfficher.getModel());
    }// GEN-LAST:event_jButtonAfficherActionPerformed

    private void jButtonResetTableAfficherActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonResetTableAfficherActionPerformed
        affichage.clearAffiche((DefaultTableModel) jTableAfficher.getModel());
    }// GEN-LAST:event_jButtonResetTableAfficherActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtnExitActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Confirm if you want to exit", "SQLite Connector",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }// GEN-LAST:event_jbtnExitActionPerformed

    private void jButtonAddIrregulierActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAddIrregulierActionPerformed
        String preterit = jtxtPreterit.getText();
        String motAnglais = jtxtEnglishVerb.getText();
        String motFrancais = jtxtMotFrancaisVI.getText();
        String pastParticiple = jtxtPastParticiple.getText();
        int ajouteVI;
        try {
            if (preterit.equals("") || motAnglais.equals("") || motFrancais.equals("") || pastParticiple.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Le(s) champ(s) sont vide(s)");
            } else {

                ajouteVI = ajouteMot.verbeIrregulier(preterit.toLowerCase(), pastParticiple.toLowerCase(),
                        motAnglais.toLowerCase(), motFrancais.toLowerCase());

                if (verifieTable.verifieEquivalence(motAnglais, motFrancais) == false) {
                    ajouteMot.ajouteEquivalence(motFrancais.toLowerCase(), motAnglais.toLowerCase());
                }

                if (ajouteVI == 1) {
                    JOptionPane.showMessageDialog(this, "This verb has been added successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Error! This verb hasn't been added!");
                }
            }
        } catch (SQLException e) {
            System.err.println(e.getMessage());

        }

    }// GEN-LAST:event_jButtonAddIrregulierActionPerformed

    private void jButtonResetIrregulierActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonResetIrregulierActionPerformed
        jtxtEnglishVerb.setText("");
        jtxtPreterit.setText("");
        jtxtMotFrancaisVI.setText("");
        jtxtPastParticiple.setText("");
    }// GEN-LAST:event_jButtonResetIrregulierActionPerformed

    private void jButtonUpdateIrregulierActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonUpdateIrregulierActionPerformed
        String preterit = jtxtPreterit.getText();
        String pastParticiple = jtxtPastParticiple.getText();
        String mot_anglais = jtxtEnglishVerb.getText();
        String mot_francais = jtxtFRE.getText();

        try {

            if (preterit.equals("") || pastParticiple.equals("")) {
                JOptionPane.showMessageDialog(this, "Le(s) champ(s) sont vide(s)");
            } else {

                if (verifieTable.verifieVerbeIrregulier(preterit, pastParticiple, mot_anglais, mot_francais) == true) {
                    JOptionPane.showMessageDialog(this, "Verbe déjà existant");
                } else {
                    updateTable.updateVerbeIrregulier(preterit.toLowerCase(), pastParticiple.toLowerCase());
                    JOptionPane.showMessageDialog(rootPane, "update reussi");
                }
            }

        } catch (SQLException e) {
            e.getMessage();
        }

    }

    // GEN-LAST:event_jButtonUpdateIrregulierActionPerformed

    private void jButtonAfficherIrregulierActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAfficherIrregulierActionPerformed
        affichage.afficherVerbeIrregulier((DefaultTableModel) jTableIrregulier.getModel());
    }// GEN-LAST:event_jButtonAfficherIrregulierActionPerformed

    private void jTableAfficherMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTableAfficherMouseClicked
        int selectRowns;
        defaultTableModel = (DefaultTableModel) jTableAfficher.getModel();
        selectRowns = jTableAfficher.getSelectedRow();

        jtxtFRE.setText(defaultTableModel.getValueAt(selectRowns, 0).toString());
        jtxtENG.setText(defaultTableModel.getValueAt(selectRowns, 1).toString());
        jtxtSynonyms.setText(defaultTableModel.getValueAt(selectRowns, 2).toString());
        jComboType.setSelectedItem(defaultTableModel.getValueAt(selectRowns, 3).toString());
        jtxtDefinition.setText(defaultTableModel.getValueAt(selectRowns, 4).toString());
        jIdDictionnaire.setText(defaultTableModel.getValueAt(selectRowns, 5).toString());

    }// GEN-LAST:event_jTableAfficherMouseClicked

    private void jTableIrregulierMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTableAfficherMouseClicked
        int selectRowns;
        defaultTableModel = (DefaultTableModel) jTableIrregulier.getModel();
        selectRowns = jTableIrregulier.getSelectedRow();

        jtxtPreterit.setText(defaultTableModel.getValueAt(selectRowns, 2).toString());
        jtxtPastParticiple.setText(defaultTableModel.getValueAt(selectRowns, 3).toString());
    }// GEN-LAST:event_jTableAfficherMouseClicked

    private void jButtonAddTypeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAddTypeActionPerformed
        String type;
        type = JOptionPane.showInputDialog("Rentre un type pour le mot");
        try {
            if (verifieTable.verifieType(type) == true) {
                JOptionPane.showMessageDialog(rootPane, "Type deja existant");
            } else {
                ajouteMot.ajouteType(type);
                jComboType.removeAllItems();
                affichage.afficherType(jComboType);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_jButtonAddTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Type;
    private javax.swing.JButton jButtonAddIrregulier;
    private javax.swing.JButton jButtonAddType;
    private javax.swing.JButton jButtonAfficher;
    private javax.swing.JButton jButtonAfficherIrregulier;
    private javax.swing.JButton jButtonResetIrregulier;
    private javax.swing.JButton jButtonResetTableAfficher;
    private javax.swing.JButton jButtonUpdateIrregulier;
    private javax.swing.JComboBox<String> jComboType;
    private javax.swing.JLabel jIdDictionnaire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAfficher;
    private javax.swing.JTable jTableIrregulier;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtDefinition;
    private javax.swing.JTextField jtxtENG;
    private javax.swing.JTextField jtxtEnglishVerb;
    private javax.swing.JTextField jtxtFRE;
    private javax.swing.JTextField jtxtMotFrancaisVI;
    private javax.swing.JTextField jtxtPastParticiple;
    private javax.swing.JTextField jtxtPreterit;
    private javax.swing.JTextField jtxtSynonyms;
    // End of variables declaration//GEN-END:variables
}
